config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'static_pages/home'

  get '/contact_me', to: 'static_pages#contact_me', as: :contact_me

  get '/about_me', to: 'static_pages#about_me', as: :about

  resources :posts

  root 'static_pages#home'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def show
		@post = Post.find(params[:id])
	end

	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.create(post_params)
		if @post.save
		  redirect_to @post
		else
			render :new
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		if @post.update_attributes(post_params)
		  redirect_to @post
		else
			render :edit
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path
	end

	private
	  
	  def post_params
	  	params.require(:post).permit(:title, :author, :body)
	  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact_me
  end

  def about_me
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Chris's Portfolio</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "My Blog", posts_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact Me", contact_me_path %></li>
        <li><%= link_to "Log In", new_user_session_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
      </ul>


    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

<%= link_to "Back", posts_path %>

app/views/posts/index.html.erb
<div class="jumbotron">
	<h1>My Posts</h1>
</div>

<div class="container">
	<% @posts.each do |post| %>
	  <h1><%= post.title %></h1>
	  <h2><%= post.author %></h2>
	  <p><%= post.body %></p>
	  <br/>

	  <%= link_to 'Show', post_path(post), class: 'btn btn-primary' %>
	<% end %>
	<br/>
	<br/>
	<%= link_to 'Back', root_path, class: 'btn btn-primary' %>
	<%= link_to 'New Post', new_post_path(@post), class: 'btn btn-primary' %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>
<br/>
<%= link_to "Back", posts_path %>

app/views/posts/show.html.erb
<div class="container">
	<h1><%= @post.title %></h1>
  <h2><%= @post.author %></h2>
    <p><%= @post.body %></p>
	  <%= link_to 'Back', posts_path, class: 'btn btn-primary' %>
	  <%= link_to 'Edit Post', edit_post_path, class: 'btn btn-warning'%>
	  <%= link_to 'Delete Post', @post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
</div>

app/views/static_pages/about_me.html.erb
<h1>About Me</h1>
<p>
  
</p>

app/views/static_pages/contact_me.html.erb
<h1>Contact Me</h1>
<p></p>

app/views/static_pages/home.html.erb
<div class="container">
	<h1>Home</h1>
	<div><%= image_tag "Mexico1.jpg", class: "img-responsive" %></div>
	<p>Welcome to my portfolio!  My name is Chris Carlson.</p>
</div>